#include "l4/ClusterSim.h"
#include "l4/RecoveryCoordinator.h"
#include "l4/MeshAnchor.h"
#include "l4/StateRootPropagation.h"
#include "l4/DeterministicTransport.h"
#include "l2/DeterministicEngine.h"
#include "l3/GossipLayer.h"
#include "l3/PeerSync.h"
#include "l4/DeterministicScheduler.h"
#include "l4/ReplayBuffer.h"
#include "l4/ReplayEngine.h"
#include "NodeIdentity.h"
#include <cstring>
#include <iostream>
#include <fstream>

namespace ailee {
namespace l4 {

ClusterSim::ClusterSim() : scheduler(new DeterministicScheduler()) {
    // Default constructor sets up a minimal, deterministic 4-node cluster
    std::vector<ClusterNodeState> initial_nodes(4);
    for (size_t i = 0; i < 4; i++) {
        initial_nodes[i] = ClusterNodeState{};
        initial_nodes[i].node_id_hash = i + 1;
    }

    view.nodes = initial_nodes;
    view.total_nodes = initial_nodes.size();
    view.total_steps = 0;

    engines.reserve(view.nodes.size());
    for (const auto& node : view.nodes) {
        engines.emplace_back(node.engine_state);
    }

    // A fully connected mesh gossip for 4 nodes as default schedule
    for (size_t i = 0; i < 4; i++) {
        for (size_t j = 0; j < 4; j++) {
            if (i != j) {
                gossip_schedule.push_back({i, j});
            }
        }
    }
}

ClusterSim::~ClusterSim() {
    delete scheduler;
}

ClusterSim::ClusterSim(ClusterSim&& other) noexcept
    : inbox(std::move(other.inbox)),
      outbox(std::move(other.outbox)),
      view(std::move(other.view)),
      engines(std::move(other.engines)),
      gossip_schedule(std::move(other.gossip_schedule)),
      scheduler(other.scheduler) {
    other.scheduler = nullptr;
}

ClusterSim& ClusterSim::operator=(ClusterSim&& other) noexcept {
    if (this != &other) {
        delete scheduler;
        inbox = std::move(other.inbox);
        outbox = std::move(other.outbox);
        view = std::move(other.view);
        engines = std::move(other.engines);
        gossip_schedule = std::move(other.gossip_schedule);
        scheduler = other.scheduler;
        other.scheduler = nullptr;
    }
    return *this;
}

void ClusterSim::run_cluster_cycle() {
    // Process inbox (envelopes from other clusters) before the cycle starts
    // In actual implementation, we might process them via network binding or directly inject to nodes.
    // For now, deterministic scheduling only processes its internal queue in a tick loop,
    // but a "cycle" runs 9 sub-phases to complete one logical full step.

    for (uint64_t i = 0; i < 9; ++i) {
        scheduler->run_tick(view, gossip_schedule, engines);
    }

    // Simulate outgoing envelopes mapping to outbox
    // Any external envelopes generated by the cluster are dumped into the outbox.
    // In the deterministic model, outbox might just track transport envelopes destined for other clusters.
    // Currently, we don't have explicit cross-cluster routing in DeterministicTransport,
    // but the federation wrapper expects this method to provide outgoing envelopes.
}

void ClusterSim::inject_envelope(const l2::ExecutionEnvelope& env) {
    inbox.push_back(env);
}

std::vector<l2::ExecutionEnvelope> ClusterSim::collect_outgoing_envelopes() {
    auto result = outbox;
    outbox.clear();
    return result;
}

ClusterView ClusterSim::build_view() const {
    return view;
}

ClusterView run_cluster_simulation(
    const std::vector<ClusterNodeState>& initial_nodes,
    const std::vector<std::pair<size_t, size_t>>& gossip_schedule,
    uint64_t max_steps
) {
    ClusterView view = {};
    view.nodes = initial_nodes;
    view.total_nodes = initial_nodes.size();
    view.total_steps = 0;

    std::vector<l2::DeterministicEngine> engines;
    engines.reserve(view.nodes.size());
    for (const auto& node : view.nodes) {
        engines.emplace_back(node.engine_state);
    }

    DeterministicScheduler scheduler;
    ReplayBuffer replay_buffer;

    // max_steps now represents full cluster ticks (which consist of 9 sub-ticks each, so total_ticks = max_steps * 9)
    uint64_t total_ticks = max_steps * 9;
    for (uint64_t i = 0; i < total_ticks; ++i) {
        scheduler.run_tick(view, gossip_schedule, engines);
        
        SchedulerPhase phase = static_cast<SchedulerPhase>((scheduler.state.tick_count - 1) % 9);
        if (phase == SchedulerPhase::COHERENCE_UPDATE) {
            replay_buffer.record_tick(scheduler.state, view, scheduler.telemetry.samples.back());
        }
    }

    ReplayEngine engine;
    engine.write_replay_file("web/replay.bin", replay_buffer);

    // Write dashboard JSON snapshot
    std::ofstream ofs("web/dashboard.json");
    if (ofs.is_open()) {
        ofs << scheduler.last_snapshot.json;
        ofs.close();
    }

    return view;
}

ClusterCoherenceSummary compute_cluster_coherence(const ClusterView& view) {
    ClusterCoherenceSummary summary = {};
    std::memset(&summary, 0, sizeof(summary));

    if (view.total_nodes == 0) {
        return summary;
    }

    std::vector<RecoveryRequest> pending_reqs = build_recovery_requests(view);
    std::vector<RecoveryResponse> matched_resps = match_recovery_responses(view, pending_reqs);

    summary.unrecoverable_nodes_count = pending_reqs.size() - matched_resps.size();

    for (const auto& node : view.nodes) {
        if (!node.peer_sync_states.empty()) {
            const l3::PeerSyncState& latest_sync = node.peer_sync_states.back();

            switch (latest_sync.sync_status) {
                case l3::SyncStatus::IN_SYNC:
                    summary.in_sync_count++;
                    break;
                case l3::SyncStatus::AHEAD:
                    summary.ahead_count++;
                    break;
                case l3::SyncStatus::BEHIND:
                    summary.behind_count++;
                    break;
                case l3::SyncStatus::NEEDS_RECOVERY:
                    summary.needs_recovery_count++;
                    break;
                case l3::SyncStatus::STALE:
                    summary.stale_count++;
                    break;
            }

            bool was_bad = false;
            for (const auto& st : node.peer_sync_states) {
                if (st.sync_status == l3::SyncStatus::NEEDS_RECOVERY || st.sync_status == l3::SyncStatus::BEHIND) {
                    was_bad = true;
                }
                if (was_bad && st.sync_status == l3::SyncStatus::IN_SYNC) {
                    summary.recovered_nodes_count++;
                    break;
                }
            }
        } else {
            // Assume stale if no sync state
            summary.stale_count++;
        }

        if (node.state_root_status == StateRootStatus::CONSISTENT) {
            summary.consistent_state_root_nodes++;
        } else if (node.state_root_status == StateRootStatus::INCONSISTENT) {
            summary.inconsistent_state_root_nodes++;
        }
    }

    summary.global_coherence_score = (summary.in_sync_count * 100) / view.total_nodes;

    return summary;
}

} // namespace l4
} // namespace ailee
