#ifndef AMBIENT_AI_EVENT_COMMITMENT_HPP
#define AMBIENT_AI_EVENT_COMMITMENT_HPP

#include <vector>
#include <string>
#include <array>
#include <cstdint>

namespace ailee {
namespace ambient {

using Hash256 = std::array<uint8_t, 32>;

constexpr size_t MAX_EVENT_PAYLOAD_SIZE = 1024; // 1 KB max

// Canonical structure for an external ambient event
struct AmbientEvent {
    Hash256 eventId;                 // Unique identifier generated by device
    std::string deviceId;            // Registered identity of the sensing device
    uint64_t logicalTimestamp;       // Protocol-defined logical tick (NOT wall-clock)
    std::vector<uint8_t> payload;    // Arbitrary binary data, <= 1024 bytes

    // Cryptographic binding over eventId || deviceId || logicalTimestamp || payload
    std::vector<uint8_t> deviceSignature;

    // Performs deterministic bounds checking and secp256k1 ECDSA verification
    bool verify() const;

    // Serializes and computes the SHA-256 hash (secp256k1 wrapper) of the event
    Hash256 hash() const;
};

// Aggregates events and interfaces with the Data Availability (DA) network
class AmbientEventAggregator {
public:
    // Pushes an event into the local pending queue.
    // Silently drops events failing verify() or exceeding MAX_EVENT_PAYLOAD_SIZE.
    bool submitEvent(const AmbientEvent& event);

    // Finalizes the epoch's event tree.
    // 1. Sorts all pending events deterministically by (logicalTimestamp, deviceId, eventId).
    // 2. Conflict resolution: If identical eventIds exist, retain the one with the lexicographically lowest deviceSignature.
    // 3. Produces a Merkle root from the sorted hashes.
    Hash256 finalizeEpochRoot() const;

    // Packages the raw events into an L2StateDiff equivalent structure for DA propagation.
    std::vector<uint8_t> exportToDAPayload() const;
};

} // namespace ambient
} // namespace ailee

#endif // AMBIENT_AI_EVENT_COMMITMENT_HPP
